[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ytshortsgenerator"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
